### ISSUE TITLE
能否加个自定义TimerId的功能

### ISSUE THREAD

**Issue by bigBron** [koangel/grapeTimer#8]
需要在定时器方法中使用到TimerId，但是TimerId是在调用添加定时器方法后才返回，或者有什么办法在定时器内方法中获取当前定时器id？
```go
	grapeTimer.NewTickerLoop(1000, -1, func() {
		// ...
		if some {
			grapeTimer.StopTimer(timerId)
		}
	})
```

**Comment by koangel** [comment]
首先不太推荐你这么写代码，建议可以在后面写一个专门STOP的函数，其次就是创建TIMER时我们才能知道TIMERID，这点是类似于JS的TIMER的（C++也是如此），所以如果你要使用闭包的话，我建议你可以写一个其他函数来负责停止或使用1次，这种方式自动停止

由于TIMER的特殊性，我们无法在TIMER创建之前得知TIMERID，这点比较麻烦

**Comment by koangel** [comment]
稍后我会考虑传入TIMERID，不过这种方式我未添加主要是担心TIMERID外部管理导致的冲突和TIMER停止异常

**Comment by bigBron** [comment]
能否把`GrapeTimer#Id`改成`string`类型？这样就能提前定义TIMERID

https://github.com/koangel/grapeTimer/blob/a32e3ae5e70c79b094543d09552b5104b325f408/timerExecute.go#L40-L50
https://github.com/koangel/grapeTimer/blob/a32e3ae5e70c79b094543d09552b5104b325f408/timerExecute.go#L136-L159

**Comment by bigBron** [comment]
或者在调用定时器callback时，判断callback类型，自动注入TimerId

**Comment by bigBron** [comment]
还有一个想法是，判断callbackfan回值，来判断是否继续执行定时器

**Comment by koangel** [comment]
无法为了你个人把TimerId改为string，这个是不行的
注入TimerId会导致推到类型和Timer本身的简洁性，同时也会造成已使用本库的同志们需要更改大量代码，也不太现实
新代码已增加PeekNextId 你可以查看一下我刚刚提交的版本

**Comment by koangel** [comment]
> 还有一个想法是，判断callbackfan回值，来判断是否继续执行定时器

因为本身它是类型推导的，返回值推导本身会造成更多损耗也不太简洁，所以我当时并未设计该系统，由于本人是C/C++工程师，所以大量代码是C/C++的影子，我司在日常使用并未感觉不妥，因为TIMERID这个主要用于异步关闭和其他函数中停止 TIMER本身，故而没有涉及到同步关闭问题，因为如果TIMER内部需要关闭的，通常我们是建议采用其他方式开启TIMER或关闭TIMER的

**Comment by koangel** [comment]
你现在可以通过：

**Comment by bigBron** [comment]
`PeekNextId`的意义是获取下一个timerId，但是内部不做任何操作，使用`PeekNextId`前提是外部能正确处理竞争问题，对吧？

**Comment by koangel** [comment]
> `PeekNextId`的意义是获取下一个timerId，但是内部不做任何操作，使用`PeekNextId`前提是外部能正确处理竞争问题，对吧？

是的，內部使用的是原子鎖
